// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package demo.interfaces.grpc;

public final class GroupOuterClass {
  private GroupOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Group)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 groupID = 1;</code>
     * @return The groupID.
     */
    long getGroupID();

    /**
     * <code>string groupParent = 2;</code>
     * @return The groupParent.
     */
    java.lang.String getGroupParent();
    /**
     * <code>string groupParent = 2;</code>
     * @return The bytes for groupParent.
     */
    com.google.protobuf.ByteString
        getGroupParentBytes();

    /**
     * <code>string groupName = 3;</code>
     * @return The groupName.
     */
    java.lang.String getGroupName();
    /**
     * <code>string groupName = 3;</code>
     * @return The bytes for groupName.
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <code>int64 groupNumberMembers = 4;</code>
     * @return The groupNumberMembers.
     */
    long getGroupNumberMembers();
  }
  /**
   * Protobuf type {@code Group}
   */
  public  static final class Group extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Group)
      GroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Group.newBuilder() to construct.
    private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Group() {
      groupParent_ = "";
      groupName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Group();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Group(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              groupID_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              groupParent_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              groupName_ = s;
              break;
            }
            case 32: {

              groupNumberMembers_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demo.interfaces.grpc.GroupOuterClass.internal_static_Group_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demo.interfaces.grpc.GroupOuterClass.internal_static_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demo.interfaces.grpc.GroupOuterClass.Group.class, demo.interfaces.grpc.GroupOuterClass.Group.Builder.class);
    }

    public static final int GROUPID_FIELD_NUMBER = 1;
    private long groupID_;
    /**
     * <code>int64 groupID = 1;</code>
     * @return The groupID.
     */
    public long getGroupID() {
      return groupID_;
    }

    public static final int GROUPPARENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object groupParent_;
    /**
     * <code>string groupParent = 2;</code>
     * @return The groupParent.
     */
    public java.lang.String getGroupParent() {
      java.lang.Object ref = groupParent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupParent_ = s;
        return s;
      }
    }
    /**
     * <code>string groupParent = 2;</code>
     * @return The bytes for groupParent.
     */
    public com.google.protobuf.ByteString
        getGroupParentBytes() {
      java.lang.Object ref = groupParent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupParent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object groupName_;
    /**
     * <code>string groupName = 3;</code>
     * @return The groupName.
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      }
    }
    /**
     * <code>string groupName = 3;</code>
     * @return The bytes for groupName.
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPNUMBERMEMBERS_FIELD_NUMBER = 4;
    private long groupNumberMembers_;
    /**
     * <code>int64 groupNumberMembers = 4;</code>
     * @return The groupNumberMembers.
     */
    public long getGroupNumberMembers() {
      return groupNumberMembers_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupID_ != 0L) {
        output.writeInt64(1, groupID_);
      }
      if (!getGroupParentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupParent_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, groupName_);
      }
      if (groupNumberMembers_ != 0L) {
        output.writeInt64(4, groupNumberMembers_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, groupID_);
      }
      if (!getGroupParentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupParent_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, groupName_);
      }
      if (groupNumberMembers_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, groupNumberMembers_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof demo.interfaces.grpc.GroupOuterClass.Group)) {
        return super.equals(obj);
      }
      demo.interfaces.grpc.GroupOuterClass.Group other = (demo.interfaces.grpc.GroupOuterClass.Group) obj;

      if (getGroupID()
          != other.getGroupID()) return false;
      if (!getGroupParent()
          .equals(other.getGroupParent())) return false;
      if (!getGroupName()
          .equals(other.getGroupName())) return false;
      if (getGroupNumberMembers()
          != other.getGroupNumberMembers()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupID());
      hash = (37 * hash) + GROUPPARENT_FIELD_NUMBER;
      hash = (53 * hash) + getGroupParent().hashCode();
      hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGroupName().hashCode();
      hash = (37 * hash) + GROUPNUMBERMEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupNumberMembers());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Group parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(demo.interfaces.grpc.GroupOuterClass.Group prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Group}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Group)
        demo.interfaces.grpc.GroupOuterClass.GroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_Group_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_Group_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                demo.interfaces.grpc.GroupOuterClass.Group.class, demo.interfaces.grpc.GroupOuterClass.Group.Builder.class);
      }

      // Construct using demo.interfaces.grpc.GroupOuterClass.Group.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        groupID_ = 0L;

        groupParent_ = "";

        groupName_ = "";

        groupNumberMembers_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_Group_descriptor;
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.Group getDefaultInstanceForType() {
        return demo.interfaces.grpc.GroupOuterClass.Group.getDefaultInstance();
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.Group build() {
        demo.interfaces.grpc.GroupOuterClass.Group result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.Group buildPartial() {
        demo.interfaces.grpc.GroupOuterClass.Group result = new demo.interfaces.grpc.GroupOuterClass.Group(this);
        result.groupID_ = groupID_;
        result.groupParent_ = groupParent_;
        result.groupName_ = groupName_;
        result.groupNumberMembers_ = groupNumberMembers_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof demo.interfaces.grpc.GroupOuterClass.Group) {
          return mergeFrom((demo.interfaces.grpc.GroupOuterClass.Group)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(demo.interfaces.grpc.GroupOuterClass.Group other) {
        if (other == demo.interfaces.grpc.GroupOuterClass.Group.getDefaultInstance()) return this;
        if (other.getGroupID() != 0L) {
          setGroupID(other.getGroupID());
        }
        if (!other.getGroupParent().isEmpty()) {
          groupParent_ = other.groupParent_;
          onChanged();
        }
        if (!other.getGroupName().isEmpty()) {
          groupName_ = other.groupName_;
          onChanged();
        }
        if (other.getGroupNumberMembers() != 0L) {
          setGroupNumberMembers(other.getGroupNumberMembers());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        demo.interfaces.grpc.GroupOuterClass.Group parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (demo.interfaces.grpc.GroupOuterClass.Group) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long groupID_ ;
      /**
       * <code>int64 groupID = 1;</code>
       * @return The groupID.
       */
      public long getGroupID() {
        return groupID_;
      }
      /**
       * <code>int64 groupID = 1;</code>
       * @param value The groupID to set.
       * @return This builder for chaining.
       */
      public Builder setGroupID(long value) {
        
        groupID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 groupID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupID() {
        
        groupID_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object groupParent_ = "";
      /**
       * <code>string groupParent = 2;</code>
       * @return The groupParent.
       */
      public java.lang.String getGroupParent() {
        java.lang.Object ref = groupParent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupParent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string groupParent = 2;</code>
       * @return The bytes for groupParent.
       */
      public com.google.protobuf.ByteString
          getGroupParentBytes() {
        java.lang.Object ref = groupParent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupParent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string groupParent = 2;</code>
       * @param value The groupParent to set.
       * @return This builder for chaining.
       */
      public Builder setGroupParent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupParent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string groupParent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupParent() {
        
        groupParent_ = getDefaultInstance().getGroupParent();
        onChanged();
        return this;
      }
      /**
       * <code>string groupParent = 2;</code>
       * @param value The bytes for groupParent to set.
       * @return This builder for chaining.
       */
      public Builder setGroupParentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupParent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupName_ = "";
      /**
       * <code>string groupName = 3;</code>
       * @return The groupName.
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string groupName = 3;</code>
       * @return The bytes for groupName.
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string groupName = 3;</code>
       * @param value The groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string groupName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupName() {
        
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <code>string groupName = 3;</code>
       * @param value The bytes for groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupName_ = value;
        onChanged();
        return this;
      }

      private long groupNumberMembers_ ;
      /**
       * <code>int64 groupNumberMembers = 4;</code>
       * @return The groupNumberMembers.
       */
      public long getGroupNumberMembers() {
        return groupNumberMembers_;
      }
      /**
       * <code>int64 groupNumberMembers = 4;</code>
       * @param value The groupNumberMembers to set.
       * @return This builder for chaining.
       */
      public Builder setGroupNumberMembers(long value) {
        
        groupNumberMembers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 groupNumberMembers = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupNumberMembers() {
        
        groupNumberMembers_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Group)
    }

    // @@protoc_insertion_point(class_scope:Group)
    private static final demo.interfaces.grpc.GroupOuterClass.Group DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new demo.interfaces.grpc.GroupOuterClass.Group();
    }

    public static demo.interfaces.grpc.GroupOuterClass.Group getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Group>
        PARSER = new com.google.protobuf.AbstractParser<Group>() {
      @java.lang.Override
      public Group parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Group(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Group> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Group> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public demo.interfaces.grpc.GroupOuterClass.Group getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responsemessage = 1;</code>
     * @return The responsemessage.
     */
    java.lang.String getResponsemessage();
    /**
     * <code>string responsemessage = 1;</code>
     * @return The bytes for responsemessage.
     */
    com.google.protobuf.ByteString
        getResponsemessageBytes();

    /**
     * <code>int32 responseCode = 2;</code>
     * @return The responseCode.
     */
    int getResponseCode();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      responsemessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new APIResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responsemessage_ = s;
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demo.interfaces.grpc.GroupOuterClass.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demo.interfaces.grpc.GroupOuterClass.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demo.interfaces.grpc.GroupOuterClass.APIResponse.class, demo.interfaces.grpc.GroupOuterClass.APIResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responsemessage_;
    /**
     * <code>string responsemessage = 1;</code>
     * @return The responsemessage.
     */
    public java.lang.String getResponsemessage() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsemessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responsemessage = 1;</code>
     * @return The bytes for responsemessage.
     */
    public com.google.protobuf.ByteString
        getResponsemessageBytes() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsemessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 2;</code>
     * @return The responseCode.
     */
    public int getResponseCode() {
      return responseCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponsemessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responsemessage_);
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponsemessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responsemessage_);
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof demo.interfaces.grpc.GroupOuterClass.APIResponse)) {
        return super.equals(obj);
      }
      demo.interfaces.grpc.GroupOuterClass.APIResponse other = (demo.interfaces.grpc.GroupOuterClass.APIResponse) obj;

      if (!getResponsemessage()
          .equals(other.getResponsemessage())) return false;
      if (getResponseCode()
          != other.getResponseCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponsemessage().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(demo.interfaces.grpc.GroupOuterClass.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        demo.interfaces.grpc.GroupOuterClass.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                demo.interfaces.grpc.GroupOuterClass.APIResponse.class, demo.interfaces.grpc.GroupOuterClass.APIResponse.Builder.class);
      }

      // Construct using demo.interfaces.grpc.GroupOuterClass.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responsemessage_ = "";

        responseCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.APIResponse getDefaultInstanceForType() {
        return demo.interfaces.grpc.GroupOuterClass.APIResponse.getDefaultInstance();
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.APIResponse build() {
        demo.interfaces.grpc.GroupOuterClass.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.APIResponse buildPartial() {
        demo.interfaces.grpc.GroupOuterClass.APIResponse result = new demo.interfaces.grpc.GroupOuterClass.APIResponse(this);
        result.responsemessage_ = responsemessage_;
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof demo.interfaces.grpc.GroupOuterClass.APIResponse) {
          return mergeFrom((demo.interfaces.grpc.GroupOuterClass.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(demo.interfaces.grpc.GroupOuterClass.APIResponse other) {
        if (other == demo.interfaces.grpc.GroupOuterClass.APIResponse.getDefaultInstance()) return this;
        if (!other.getResponsemessage().isEmpty()) {
          responsemessage_ = other.responsemessage_;
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        demo.interfaces.grpc.GroupOuterClass.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (demo.interfaces.grpc.GroupOuterClass.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responsemessage_ = "";
      /**
       * <code>string responsemessage = 1;</code>
       * @return The responsemessage.
       */
      public java.lang.String getResponsemessage() {
        java.lang.Object ref = responsemessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responsemessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @return The bytes for responsemessage.
       */
      public com.google.protobuf.ByteString
          getResponsemessageBytes() {
        java.lang.Object ref = responsemessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responsemessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @param value The responsemessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponsemessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responsemessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponsemessage() {
        
        responsemessage_ = getDefaultInstance().getResponsemessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @param value The bytes for responsemessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponsemessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responsemessage_ = value;
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 2;</code>
       * @return The responseCode.
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final demo.interfaces.grpc.GroupOuterClass.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new demo.interfaces.grpc.GroupOuterClass.APIResponse();
    }

    public static demo.interfaces.grpc.GroupOuterClass.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      @java.lang.Override
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public demo.interfaces.grpc.GroupOuterClass.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demo.interfaces.grpc.GroupOuterClass.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demo.interfaces.grpc.GroupOuterClass.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demo.interfaces.grpc.GroupOuterClass.Empty.class, demo.interfaces.grpc.GroupOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof demo.interfaces.grpc.GroupOuterClass.Empty)) {
        return super.equals(obj);
      }
      demo.interfaces.grpc.GroupOuterClass.Empty other = (demo.interfaces.grpc.GroupOuterClass.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.interfaces.grpc.GroupOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(demo.interfaces.grpc.GroupOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        demo.interfaces.grpc.GroupOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                demo.interfaces.grpc.GroupOuterClass.Empty.class, demo.interfaces.grpc.GroupOuterClass.Empty.Builder.class);
      }

      // Construct using demo.interfaces.grpc.GroupOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return demo.interfaces.grpc.GroupOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.Empty getDefaultInstanceForType() {
        return demo.interfaces.grpc.GroupOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.Empty build() {
        demo.interfaces.grpc.GroupOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public demo.interfaces.grpc.GroupOuterClass.Empty buildPartial() {
        demo.interfaces.grpc.GroupOuterClass.Empty result = new demo.interfaces.grpc.GroupOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof demo.interfaces.grpc.GroupOuterClass.Empty) {
          return mergeFrom((demo.interfaces.grpc.GroupOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(demo.interfaces.grpc.GroupOuterClass.Empty other) {
        if (other == demo.interfaces.grpc.GroupOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        demo.interfaces.grpc.GroupOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (demo.interfaces.grpc.GroupOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final demo.interfaces.grpc.GroupOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new demo.interfaces.grpc.GroupOuterClass.Empty();
    }

    public static demo.interfaces.grpc.GroupOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public demo.interfaces.grpc.GroupOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Group_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Group_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013group.proto\"\\\n\005Group\022\017\n\007groupID\030\001 \001(\003\022" +
      "\023\n\013groupParent\030\002 \001(\t\022\021\n\tgroupName\030\003 \001(\t\022" +
      "\032\n\022groupNumberMembers\030\004 \001(\003\"<\n\013APIRespon" +
      "se\022\027\n\017responsemessage\030\001 \001(\t\022\024\n\014responseC" +
      "ode\030\002 \001(\005\"\007\n\005Empty2\255\001\n\014GroupService\022\034\n\010g" +
      "etGroup\022\006.Group\032\006.Group\"\000\022 \n\nlistGroups\022" +
      "\006.Empty\032\006.Group\"\0000\001\022-\n\021batchCreateGroups" +
      "\022\006.Group\032\014.APIResponse\"\000(\001\022.\n\020bidiUpdate" +
      "Groups\022\006.Group\032\014.APIResponse\"\000(\0010\001B\026\n\024de" +
      "mo.interfaces.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Group_descriptor,
        new java.lang.String[] { "GroupID", "GroupParent", "GroupName", "GroupNumberMembers", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
